### ISSUE TITLE
add a "Working" screen

### ISSUE THREAD

**Issue by builder555** [builder555/PineSAM#48]
The screen should:

- [x] display current temperature
- [x] display current wattage
- [x] display max wattage
- [x] display current voltage
~-  display max voltage~
- [x] be able to change set temperature

Backend:
- [x] check which data is available from iron
- [x] fetch live data every 2000ms
- [x] push data to WS

**Comment by River-b** [comment]
ty for making this ticket much cleaner and more organized

**Comment by builder555** [comment]
can read:

LiveTemp
SetTemp
Voltage
HandleTemp
PWMLevel
PowerSource
TipResistance
Uptime
MovementTime
MaxTipTempAbility
uVoltsTip
HallSensor
OperatingMode
Watts

but reading all of them slows down the device and BLE communication. for the sake of speed and better UX, only these values will be returned:

LiveTemp
Voltage
HandleTemp
OperatingMode
Watts

**Comment by River-b** [comment]
Sounds good. most of those are DEbug info that would not need to be displayed in the Work view,
I was thinking maybe add an extra section to Settings called "Debug Data"
and put most of that in there. some of it actually doesn't change and is static . 

if you don't put it on Work View and it's on another Settings that does't ask for it until we get to that section does that help? 
We  need: Set temp, LiveTemp, handle temp, watts for sure.

I dont know what VoltsTip is. 
TipResistance is a one time static number it picks either 6.2 ohm or 8 ohm profile when Pinecil first boots depending on the tip you have installed at initial boot since it only reads at boot. once you get that you dont have to get it again unless pinecil is rebooted. so that tells us what kind of Tip Profile is being used but doesn't need to be constantly requested.

**Comment by River-b** [comment]
"uVoltsTip"
[T] <Ralimtek> micro-volts raw reading of the tip.
Same as in debug menu

I think this is R-Tip then per documents [debug details ](https://ralim.github.io/IronOS/DebugMenu/)
and would only be needed for Diagnostics and troubleshooting and not for active view.

**Comment by River-b** [comment]
will hall sensor still be in the Sleep settings sector?

**Comment by builder555** [comment]
> will hall sensor still be in the Sleep settings sector?

that's for #33

**Comment by River-Mochi** [comment]
For reference
1. add  Double  Arrow icon to "Peak Watts" that Builder found. 

- either:   [skinnier one](https://www.iconfinder.com/search?q=double&iconset=font-awesome)
- or: [Thicker](https://www.iconfinder.com/icons/8541581/angle_double_up_icon)
Skinny one might look better, needs testing.

**Comment by builder555** [comment]
as per our discussion, removing "max voltage" from acceptance criteria
